# These are supported funding model platforms

github: marcelklehr # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: marcelklehr
open_collective: floccus
liberapay: marcelklehr
ko_fi: marcelklehr
custom: https://www.paypal.com/donate/?hosted_button_id=R3SDCC7AFSYZU
